<a href="https://colab.research.google.com/github/Abhilash1001/Thesis_Work/blob/master/Thesis_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np # linear algebra
import pandas as pd # data processing, 

import seaborn as sns

%matplotlib inline 
import matplotlib.pyplot as plt # side-stepping mpl backend
import matplotlib.gridspec as gridspec # subplots


#Import models from scikit learn module:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Renewed_Dataset.csv to Renewed_Dataset.csv

In [37]:
import io
datset = pd.read_csv(io.BytesIO(uploaded['Renewed_Dataset.csv']))
datset

     pl_letter  pl_controvflag  pl_pnum  ...  st_acts  st_actr  st_actlx
0            b               0        1  ...      NaN      NaN       NaN
1            b               0        1  ...      NaN      NaN       NaN
2            b               0        1  ...    0.095      NaN       NaN
3            b               0        1  ...    0.161    -5.06       NaN
4            b               0        1  ...    0.148    -5.08       NaN
...        ...             ...      ...  ...      ...      ...       ...
4192         b               0        1  ...      NaN      NaN       NaN
4193         b               0        3  ...    0.146    -5.04     28.13
4194         c               0        3  ...    0.146    -5.04     28.13
4195         d               0        3  ...    0.146    -5.04     28.13
4196         b               0        1  ...    0.102      NaN       NaN

[4197 rows x 69 columns]

In [38]:
#Converting Categorical column pl_letter
datset['pl_letter']=datset['pl_letter'].map({'b':0, 'c':1, 'd':2, 'e':3, 'f':4, 'g':5, 'h':6, 'i':7})
datset['pl_bmassprov']=datset['pl_bmassprov'].map({'Mass':1, 'Msin(i)/sin(i)':2, 'Msini':3})
datset['st_optband']=datset['st_optband'].map({'Kepler-band':1, 'V (Johnson)':2})
datset

      pl_letter  pl_controvflag  pl_pnum  ...  st_acts  st_actr  st_actlx
0             0               0        1  ...      NaN      NaN       NaN
1             0               0        1  ...      NaN      NaN       NaN
2             0               0        1  ...    0.095      NaN       NaN
3             0               0        1  ...    0.161    -5.06       NaN
4             0               0        1  ...    0.148    -5.08       NaN
...         ...             ...      ...  ...      ...      ...       ...
4192          0               0        1  ...      NaN      NaN       NaN
4193          0               0        3  ...    0.146    -5.04     28.13
4194          1               0        3  ...    0.146    -5.04     28.13
4195          2               0        3  ...    0.146    -5.04     28.13
4196          0               0        1  ...    0.102      NaN       NaN

[4197 rows x 69 columns]

In [39]:
#Dropping unwanted columns
datset.drop(["ra_str", "dec_str", "hd_name", "hip_name"], axis = 1, inplace = True)
datset

      pl_letter  pl_controvflag  pl_pnum  ...  st_acts  st_actr  st_actlx
0             0               0        1  ...      NaN      NaN       NaN
1             0               0        1  ...      NaN      NaN       NaN
2             0               0        1  ...    0.095      NaN       NaN
3             0               0        1  ...    0.161    -5.06       NaN
4             0               0        1  ...    0.148    -5.08       NaN
...         ...             ...      ...  ...      ...      ...       ...
4192          0               0        1  ...      NaN      NaN       NaN
4193          0               0        3  ...    0.146    -5.04     28.13
4194          1               0        3  ...    0.146    -5.04     28.13
4195          2               0        3  ...    0.146    -5.04     28.13
4196          0               0        1  ...    0.102      NaN       NaN

[4197 rows x 65 columns]

In [40]:
pd.set_option('display.max_rows', 500)

In [41]:
datset.mean(axis = 0)

pl_letter         3.988563e-01
pl_controvflag    4.288778e-03
pl_pnum           1.781511e+00
pl_orbper         2.116647e+03
pl_orbsmax        9.053798e+00
pl_orbeccen       1.578174e-01
pl_orbincl        8.645189e+01
pl_bmassj         2.445932e+00
pl_bmassprov      1.886090e+00
pl_radj           3.827016e-01
pl_dens           2.560557e+00
pl_ttvflag        7.553014e-02
ra                2.433550e+02
dec               2.224804e+01
st_dist           6.370873e+02
gaia_dist         5.930438e+02
st_optmag         1.265103e+01
st_optband        1.420075e+00
gaia_gmag         1.254021e+01
st_teff           5.483415e+03
st_mass           9.905394e-01
st_rad            1.551982e+00
pl_tranflag       7.648320e-01
pl_rvflag         3.509650e-01
pl_astflag        2.387775e-03
pl_omflag         6.909697e-03
pl_cbflag         9.292352e-03
pl_angsep         1.974956e+02
pl_orbtper        2.454934e+06
pl_orblper        1.336767e+02
pl_eqt            1.110160e+03
pl_massj          2.102539e+00
pl_msinij         2.802143e+00
pl_masse          6.680026e+02
pl_msinie         8.905329e+02
pl_bmasse         7.772199e+02
pl_rade           4.289161e+00
pl_rads           3.933790e-02
pl_trandep        8.185392e-01
pl_trandur        1.678204e-01
pl_tranmid        2.455536e+06
pl_imppar         4.086492e-01
pl_occdep         1.160706e-02
pl_ratdor         2.582440e+01
pl_ratror         3.689395e-02
pl_status         3.000000e+00
pl_mnum           0.000000e+00
pl_st_npar        3.601430e+01
st_plx            1.803032e+01
gaia_plx          1.129402e+01
st_pm             1.017392e+02
gaia_pm           9.789769e+01
st_radv          -2.078168e+00
st_sp             4.853385e+00
st_logg           4.352413e+00
st_lum           -2.042975e-01
st_dens           2.928560e+00
st_metfe          1.524718e-02
st_metratio       1.164165e+00
st_age            4.185112e+00
st_vsini          5.254729e+00
st_acts           3.340573e-01
st_actr          -4.979953e+00
st_actlx          2.759125e+01
dtype: float64

In [42]:
datset.fillna(datset.mean())
datset=datset.fillna(datset.mean())

In [43]:
train, validate, test = np.split(datset.sample(frac=1), [int(.6*len(datset)), int(.8*len(datset))])
train

      pl_letter  pl_controvflag  pl_pnum  ...   st_acts   st_actr  st_actlx
2389          3               0        6  ...  0.334057 -4.979953  27.59125
452           0               0        1  ...  0.142000 -5.140000  27.59125
1086          0               0        1  ...  0.334057 -4.979953  27.59125
3758          0               0        1  ...  0.334057 -4.979953  27.59125
3817          0               0        1  ...  0.334057 -4.979953  27.59125
...         ...             ...      ...  ...       ...       ...       ...
1518          0               0        4  ...  0.334057 -4.979953  27.59125
2958          1               0        2  ...  0.334057 -4.979953  27.59125
2395          1               0        2  ...  0.334057 -4.979953  27.59125
1611          0               0        1  ...  0.334057 -4.979953  27.59125
3719          0               0        1  ...  0.334057 -4.979953  27.59125

[2518 rows x 65 columns]