<a href="https://colab.research.google.com/github/Abhilash1001/hello-world/blob/master/Thesis_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, 

import seaborn as sns

%matplotlib inline 
import matplotlib.pyplot as plt # side-stepping mpl backend
import matplotlib.gridspec as gridspec # subplots


#Import models from scikit learn module:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [ ]:
from google.colab import files
uploaded = files.upload()

In [8]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['confirmed_planets.csv']))
dataset

     pl_letter  pl_controvflag  pl_pnum  ...  st_raderr1  st_raderr2  st_radlim
0            b               0        1  ...        2.00       -2.00        0.0
1            b               0        1  ...        2.84       -2.84        0.0
2            b               0        1  ...        1.00       -1.00        0.0
3            b               0        1  ...        0.01       -0.01        0.0
4            b               0        1  ...        0.01       -0.01        0.0
...        ...             ...      ...  ...         ...         ...        ...
4159         b               0        1  ...        0.70       -0.70        0.0
4160         b               0        3  ...         NaN         NaN        0.0
4161         c               0        3  ...         NaN         NaN        0.0
4162         d               0        3  ...         NaN         NaN        0.0
4163         b               0        1  ...         NaN         NaN        0.0

[4164 rows x 67 columns]

In [9]:
#Converting Categorical column pl_letter
dataset['pl_letter']=dataset['pl_letter'].map({'b':0, 'c':1, 'd':2, 'e':3, 'f':4, 'g':5, 'h':6, 'i':7})
dataset['pl_bmassprov']=dataset['pl_bmassprov'].map({'Mass':1, 'Msin(i)/sin(i)':2, 'Msini':2})
dataset['st_optband']=dataset['st_optband'].map({'Kepler-band':1, 'V (Johnson)':2})
dataset

      pl_letter  pl_controvflag  pl_pnum  ...  st_raderr1  st_raderr2  st_radlim
0             0               0        1  ...        2.00       -2.00        0.0
1             0               0        1  ...        2.84       -2.84        0.0
2             0               0        1  ...        1.00       -1.00        0.0
3             0               0        1  ...        0.01       -0.01        0.0
4             0               0        1  ...        0.01       -0.01        0.0
...         ...             ...      ...  ...         ...         ...        ...
4159          0               0        1  ...        0.70       -0.70        0.0
4160          0               0        3  ...         NaN         NaN        0.0
4161          1               0        3  ...         NaN         NaN        0.0
4162          2               0        3  ...         NaN         NaN        0.0
4163          0               0        1  ...         NaN         NaN        0.0

[4164 rows x 67 columns]

In [10]:
#Dropping unwanted columns
dataset.drop(['ra_str', 'dec_str', 'gaia_distlim', 'st_optmaglim', 'gaia_gmagerr', 'gaia_gmaglim', 'st_tefflim', 'st_masslim', 'st_radlim'],  axis = 1)

      pl_letter  pl_controvflag  pl_pnum  ...  st_rad  st_raderr1  st_raderr2
0             0               0        1  ...   19.00        2.00       -2.00
1             0               0        1  ...   29.79        2.84       -2.84
2             0               0        1  ...   11.00        1.00       -1.00
3             0               0        1  ...    0.93        0.01       -0.01
4             0               0        1  ...    1.13        0.01       -0.01
...         ...             ...      ...  ...     ...         ...         ...
4159          0               0        1  ...   26.80        0.70       -0.70
4160          0               0        3  ...    1.56         NaN         NaN
4161          1               0        3  ...    1.56         NaN         NaN
4162          2               0        3  ...    1.56         NaN         NaN
4163          0               0        1  ...   12.00         NaN         NaN

[4164 rows x 58 columns]

In [11]:
train, validate, test = np.split(dataset.sample(frac=1), [int(.6*len(dataset)), int(.8*len(dataset))])
train

      pl_letter  pl_controvflag  pl_pnum  ...  st_raderr1  st_raderr2  st_radlim
3469          1               0        6  ...        0.02       -0.02        0.0
3569          0               0        1  ...        0.31       -0.13        0.0
3261          0               0        1  ...        0.03       -0.02        0.0
2935          1               0        3  ...        0.24       -0.24        0.0
2004          1               0        2  ...         NaN         NaN        0.0
...         ...             ...      ...  ...         ...         ...        ...
3414          3               0        4  ...        0.31       -0.23        0.0
837           0               0        1  ...        0.01       -0.01        0.0
3101          0               0        1  ...        0.02       -0.02        0.0
3478          0               0        2  ...        0.13       -0.09        0.0
3554          0               0        1  ...        0.04       -0.04        0.0

[2498 rows x 67 columns]